### ISSUE TITLE
Continuous error - Task exception was never retrieved

### ISSUE THREAD

**Issue by N1c093** [fwmarcel/home-assistant-divera#1]
Hello,

when there is currently no active alarm, I get the following error every minute:

```
2022-03-02 11:43:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/divera/sensor.py", line 133, in state
    result = self._connector.get_last_alarm()
  File "/config/custom_components/divera/connector.py", line 96, in get_last_alarm
    last_alarm_id = self.data["data"]["alarm"]["sorting"][0]
IndexError: list index out of range
```

I think, it try to parse through the index, but without any active alarm, there isn't any index 0.

Thank you in advance.

**Comment by fwmarcel** [comment]
Hello, 

thank you for the hint. 
Your assumption is correct. 
Due to the volume of operations, such a situation has not yet occurred in my system.

I put this on my todo list.

**Comment by fwmarcel** [comment]
Hello @N1c093 i have released a version in which the error should not occur. However, I have not yet encountered the case that no alarm occurred.

**Comment by N1c093** [comment]
Thank you for the new release. For now the error seems to be gone.

I will have a look how the integration behave, when there is the next alarm. I will report back.

**Comment by fwmarcel** [comment]
@N1c093 thanks for the feedback and for the integration icon ;)

**Comment by N1c093** [comment]
@fwmarcel You are welcome. As I'm not that familiar with coding, I try to contribute in another way to open source projects  :)
